#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
source /container/defaults/zabbix
source /container/defaults/zabbix-webservice
SERVICE_NAME="zabbix-webservice"

check_container_initialized
liftoff

print_start "Starting Zabbix Web Service $(zabbix_web_service -V | head -n 1 | awk '{print $NF}')"
silent exec s6-setuidgid ${ZABBIX_USER} zabbix_web_service -c "${ZABBIX_WEBSERVICE_CONFIG_PATH%/}"/"${ZABBIX_WEBSERVICE_CONFIG_FILE}"
